# Generated by Django 4.2.2 on 2023-06-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=30)),
                ('precio', models.ImageField(upload_to='')),
                ('fecha_de_oferta', models.DateField()),
            ],
        ),
    ]
