# Generated by Django 4.2.2 on 2023-07-08 20:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_comprar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprar',
        ),
        migrations.AddField(
            model_name='vender',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
