# Generated by Django 4.2.3 on 2023-07-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_vender_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vender',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_articulos'),
        ),
    ]
