# Generated by Django 4.2.3 on 2023-07-11 01:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_delete_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='datos_personales',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
